### ISSUE TITLE
Making readme complete

### ISSUE THREAD

**Issue by web3Gurung** [JejomStark/ShellOnStark#3]
Hey Jejom!
Great work so far!

Was thinking if we can make readme better with respect to readability?
Here are some ways: 
1. https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
2. https://www.makeareadme.com/
3. https://readme.so/

I can work on this, just let me know if I can go ahead and I'll raise a PR in the weekend!

**Comment by JejomStark** [comment]
Readme updated this morning, thanks for the feedback
